export const partners = [
    { logoUrl: '/images/logos/aboveit.svg', name: 'Aboveit', homepageUrl: 'https://www.aboveit.no/' },
    {
        logoUrl: '/images/logos/accenture.svg',
        name: 'Accenture',
        homepageUrl: 'https://www.accenture.com/no-en',
    },
    { logoUrl: '/images/logos/arktekk.svg', name: 'Arktekk', homepageUrl: 'https://arktekk.no/' },
    { logoUrl: '/images/logos/bekk.svg', name: 'Bekk Consulting AS', homepageUrl: 'https://www.bekk.no/' },
    { logoUrl: '/images/logos/bouvet.svg', name: 'Bouvet Norge AS', homepageUrl: 'https://www.bouvet.no/' },
    { logoUrl: '/images/logos/buypass.svg', name: 'Buypass AS', homepageUrl: 'https://www.buypass.no/' },
    {
        logoUrl: '/images/logos/capgemini.svg',
        name: 'Capgemini AS',
        homepageUrl: 'https://www.capgemini.com/no-no/',
    },
    { logoUrl: '/images/logos/capra.svg', name: 'Capra', homepageUrl: 'https://www.capraconsulting.no/' },
    { logoUrl: '/images/logos/cgi.svg', name: 'Cegal', homepageUrl: 'https://www.cegal.com/no/' },
    {
        logoUrl: '/images/logos/cloudberries.svg',
        name: 'Cloudberries AS',
        homepageUrl: 'https://www.cloudberries.no/',
    },
    { logoUrl: '/images/logos/computas.svg', name: 'Computas AS', homepageUrl: 'https://computas.com/' },
    { logoUrl: '/images/logos/dnb.svg', name: 'DNB', homepageUrl: 'https://www.dnb.no/' },
    { logoUrl: '/images/logos/elastic.svg', name: 'Elastic', homepageUrl: 'https://www.elastic.co/' },
    { logoUrl: '/images/logos/embriq.svg', name: 'Embriq AS', homepageUrl: 'https://embriq.no/' },
    { logoUrl: '/images/logos/entur.svg', name: 'Entur AS', homepageUrl: 'https://om.entur.no/om-entur/' },
    { logoUrl: '/images/logos/experis.svg', name: 'Experis AS', homepageUrl: 'https://www.experis.no/' },
    { logoUrl: '/images/logos/finn.svg', name: 'FINN.no', homepageUrl: 'https://www.finn.no/' },
    {
        logoUrl: '/images/logos/fremtind.svg',
        name: 'Fremtind Forsikring AS',
        homepageUrl: 'https://www.fremtind.no/',
    },
    {
        logoUrl: '/images/logos/gjensidige.svg',
        name: 'Gjensidige',
        homepageUrl: 'https://www.gjensidige.no/',
    },
    { logoUrl: '/images/logos/google.svg', name: 'Google', homepageUrl: 'https://www.google.com/' },
    { logoUrl: '/images/logos/husbanken.svg', name: 'Husbanken', homepageUrl: 'https://www.husbanken.no/' },
    { logoUrl: '/images/logos/itera.svg', name: 'Itera', homepageUrl: 'https://www.itera.com/no/' },
    { logoUrl: '/images/logos/kantega.svg', name: 'Kantega AS', homepageUrl: 'https://kantega.no/' },
    { logoUrl: '/images/logos/knowit.svg', name: 'Knowit AS', homepageUrl: 'https://www.knowit.no/' },
    { logoUrl: '/images/logos/kodemaker.svg', name: 'Kodemaker', homepageUrl: 'https://www.kodemaker.no/' },
    { logoUrl: '/images/logos/miles.svg', name: 'Miles', homepageUrl: 'https://www.miles.no/' },
    { logoUrl: '/images/logos/nav.svg', name: 'NAV IT', homepageUrl: 'https://www.detsombetyrnoe.no/' },
    {
        logoUrl: '/images/logos/netcompany.svg',
        name: 'Netcompany',
        homepageUrl: 'https://www.netcompany.com/no/',
    },
    {
        logoUrl: '/images/logos/norsktipping.svg',
        name: 'Norsk Tipping AS',
        homepageUrl: 'https://www.norsk-tipping.no/',
    },{
        logoUrl: '/images/logos/novari.svg',
        name: 'Novari IKS',
        homepageUrl: 'https://www.vigoiks.no/',
    },
    {
        logoUrl: '/images/logos/oslo.svg',
        name: 'Oslo Origo', // todo: sjekk
        homepageUrl: 'https://www.oslo.kommune.no/etater-foretak-og-ombud/oslo-origo/#gref',
    },
    {
        logoUrl: '/images/logos/politietpit.svg',
        name: 'Politiets IT-enhet',
        homepageUrl: 'https://www.politiet.no/om-politiet/organisasjonen/sarorganene/pit/',
    },
    {
        logoUrl: '/images/logos/postenbring.svg',
        name: 'Posten Norge AS',
        homepageUrl: 'https://www.postennorge.no/',
    },
    {
        logoUrl: '/images/logos/protector.svg',
        name: 'Protector Forsikring',
        homepageUrl: 'https://protectorforsikring.no/',
    },
    { logoUrl: '/images/logos/redhat.svg', name: 'Red Hat', homepageUrl: 'https://www.redhat.com/en' },
    { logoUrl: '/images/logos/safetywing.svg', name: 'SafetyWing', homepageUrl: 'https://safetywing.com/' },
    { logoUrl: '/images/logos/scelto.svg', name: 'Scelto AS', homepageUrl: 'https://scelto.no/' },
    { logoUrl: '/images/logos/scienta.svg', name: 'Scienta ', homepageUrl: 'https://careers.scienta.no/' },
    {
        logoUrl: '/images/logos/skatteetaten.svg',
        name: 'Skatteetaten',
        homepageUrl: 'https://www.skatteetaten.no/jobb/',
    },
    {
        logoUrl: '/images/logos/soprasteria.svg',
        name: 'Sopra Steria AS',
        homepageUrl: 'https://www.soprasteria.no/',
    },
    {
        logoUrl: '/images/logos/sparebank1.svg',
        name: 'SpareBank 1 Utvikling',
        homepageUrl: 'https://sparebank1.dev/',
    },{
        logoUrl: '/images/logos/spirgroup.svg',
        name: 'Spir Group ASA',
        homepageUrl: 'https://spirgroup.com/',
    },
    {
        logoUrl: '/images/logos/ssb.svg',
        name: 'SSB - Statistisk Sentralbyrå',
        homepageUrl: 'https://www.ssb.no/',
    },
    {
        logoUrl: '/images/logos/statensvegvesen.svg',
        name: 'Statens Vegvesen',
        homepageUrl: 'https://www.vegvesen.no/',
    },
    { logoUrl: '/images/logos/statnett.svg', name: 'Statnett SF', homepageUrl: 'https://www.statnett.no/' },
    {
        logoUrl: '/images/logos/storebrand.svg',
        name: 'Storebrand',
        homepageUrl: 'https://www.storebrand.no/',
    },
    { logoUrl: '/images/logos/systek.svg', name: 'Systek', homepageUrl: 'https://www.systek.no/' },
    { logoUrl: '/images/logos/techpros.svg', name: 'Techpros AS', homepageUrl: 'https://www.techpros.no/' },
    { logoUrl: '/images/logos/telenor.svg', name: 'Telenor Norge', homepageUrl: 'https://www.telenor.no/' },
    {
        logoUrl: '/images/logos/tietoevry.svg',
        name: 'Tietoevry',
        homepageUrl: 'https://www.tietoevry.com/no/',
    },
    { logoUrl: '/images/logos/tolletaten.svg', name: 'Tolletaten', homepageUrl: 'https://www.toll.no/' },
    {
        logoUrl: '/images/logos/tripletex.svg',
        name: 'Tripletex AS',
        homepageUrl: 'https://www.tripletex.no/',
    },
    { logoUrl: '/images/logos/twoday.svg', name: 'Twoday AS', homepageUrl: 'https://www.twoday.no' },
    {
        logoUrl: '/images/logos/uptime.svg',
        name: 'Uptime Consulting AS',
        homepageUrl: 'https://www.uptimeconsulting.no/',
    },
    { logoUrl: 'images/logos/vaadin.svg', name: 'Vaadin', homepageUrl: 'https://vaadin.com/' },
    { logoUrl: '/images/logos/webstep.svg', name: 'Webstep AS', homepageUrl: 'https://www.webstep.no/' },
]
