export const partners = [
    { logoUrl: '/logos/aboveit.svg', name: 'Aboveit', homepageUrl: 'https://www.aboveit.no/' },
    {
        logoUrl: '/logos/accenture.svg',
        name: 'Accenture',
        homepageUrl: 'https://www.accenture.com/no-en',
    },
    {
        logoUrl: '/logos/apotek1.svg',
        name: 'Apotek 1 Gruppen',
        homepageUrl: 'https://www.apotek1.no/om-apotek1',
    },
    { logoUrl: '/logos/arktekk.svg', name: 'Arktekk', homepageUrl: 'https://arktekk.no/' },
    { logoUrl: '/logos/bankid.svg', name: 'BankIdBankAxept', homepageUrl: 'https://bidbax.no' },
    { logoUrl: '/logos/bekk.svg', name: 'Bekk Consulting AS', homepageUrl: 'https://www.bekk.no/' },
    { logoUrl: '/logos/bouvet.svg', name: 'Bouvet Norge AS', homepageUrl: 'https://www.bouvet.no/' },
    { logoUrl: '/logos/buypass.svg', name: 'Buypass AS', homepageUrl: 'https://www.buypass.no/' },
    {
        logoUrl: '/logos/capgemini.svg',
        name: 'Capgemini AS',
        homepageUrl: 'https://www.capgemini.com/no-no/',
    },
    { logoUrl: '/logos/capra.svg', name: 'Capra', homepageUrl: 'https://www.capraconsulting.no/' },
    { logoUrl: '/logos/cegal.svg', name: 'Cegal', homepageUrl: 'https://www.cegal.com/no/' },
    {
        logoUrl: '/logos/cloudberries.svg',
        name: 'Cloudberries AS',
        homepageUrl: 'https://www.cloudberries.no/',
    },
    { logoUrl: '/logos/computas.svg', name: 'Computas AS', homepageUrl: 'https://computas.com/' },
    {
        logoUrl: '/logos/dfindconsulting.svg',
        name: 'Dfind Consulting',
        homepageUrl: 'https://www.dfindconsulting.no.',
    },
    {
        logoUrl: '/logos/digdir.svg',
        name: 'Digi0taliseringsdirektoratet',
        homepageUrl: 'https://www.digdir.no/',
    },
    { logoUrl: '/logos/dnb.svg', name: 'DNB', homepageUrl: 'https://www.dnb.no/' },
    { logoUrl: '/logos/eika.svg', name: 'Eika', homepageUrl: 'https://www.eika.no/' },
    { logoUrl: '/logos/elastic.svg', name: 'Elastic', homepageUrl: 'https://www.elastic.co/' },
    { logoUrl: '/logos/embriq.svg', name: 'Embriq AS', homepageUrl: 'https://embriq.no/' },
    { logoUrl: '/logos/enonic.svg', name: 'Enonic', homepageUrl: 'https://enonic.com' },
    { logoUrl: '/logos/entur.svg', name: 'Entur AS', homepageUrl: 'https://om.entur.no/om-entur/' },
    { logoUrl: '/logos/fink.svg', name: 'Fink AS', homepageUrl: 'https://bok.fink.no' },
    { logoUrl: '/logos/finn.svg', name: 'FINN.no', homepageUrl: 'https://www.finn.no/' },
    {
        logoUrl: '/logos/fremtind.svg',
        name: 'Fremtind Forsikring AS',
        homepageUrl: 'https://www.fremtind.no/',
    },
    {
        logoUrl: '/logos/gjensidige.svg',
        name: 'Gjensidige',
        homepageUrl: 'https://www.gjensidige.no/',
    },
    { logoUrl: '/logos/google.svg', name: 'Google', homepageUrl: 'https://www.google.com/' },
    { logoUrl: '/logos/inmeta.svg', name: 'Inmeta Consulting AS', homepageUrl: 'https://inmeta.no/' },
    { logoUrl: '/logos/itera.svg', name: 'Itera', homepageUrl: 'https://www.itera.com/no/' },
    { logoUrl: '/logos/iver.svg', name: 'Iver', homepageUrl: 'https://www.iver.com/' },
    { logoUrl: '/logos/jpro.svg', name: 'JProfessionals AS', homepageUrl: 'https://jpro.no/' },
    { logoUrl: '/logos/kantega.svg', name: 'Kantega AS', homepageUrl: 'https://kantega.no/' },
    { logoUrl: '/logos/knowit.svg', name: 'Knowit AS', homepageUrl: 'https://www.knowit.no/' },
    { logoUrl: '/logos/kodemaker.svg', name: 'Kodemaker', homepageUrl: 'https://www.kodemaker.no/' },
    {
        logoUrl: '/logos/enso.svg',
        name: 'Konsulentselskapet Ensō AS',
        homepageUrl: 'https://www.enso.no/',
    },
    { logoUrl: '/logos/kosli.svg', name: 'Kosli', homepageUrl: 'https://www.kosli.com/' },
    {
        logoUrl: '/logos/kraftlauget.svg',
        name: 'Kraftlauget',
        homepageUrl: 'https://kraftlauget.no/',
    },
    {
        logoUrl: '/logos/mastercard.svg',
        name: 'Mastercard',
        homepageUrl: 'https://www.mastercard.no/no-no.html',
    },
    { logoUrl: '/logos/miles.svg', name: 'Miles', homepageUrl: 'https://www.miles.no/' },
    { logoUrl: '/logos/nav.svg', name: 'NAV IT', homepageUrl: 'https://www.detsombetyrnoe.no/' },
    {
        logoUrl: '/logos/netcompany.svg',
        name: 'Netcompany',
        homepageUrl: 'https://www.netcompany.com/no/',
    },
    {
        logoUrl: '/logos/orangebusiness.svg',
        name: 'Orange Business Services AS',
        homepageUrl: 'https://www.orange-business.com/',
    },
    {
        logoUrl: '/logos/oslo.svg',
        name: 'Oslo Origo',
        homepageUrl: 'https://www.oslo.kommune.no/etater-foretak-og-ombud/oslo-origo/#gref',
    },
    {
        logoUrl: '/logos/politietpit.svg',
        name: 'Politiets IT-enhet',
        homepageUrl: 'https://www.politiet.no/om-politiet/organisasjonen/sarorganene/pit/',
    },
    {
        logoUrl: '/logos/postenbring.svg',
        name: 'Posten Norge AS',
        homepageUrl: 'https://www.postennorge.no/',
    },
    {
        logoUrl: '/logos/protector.svg',
        name: 'Protector Forsikring',
        homepageUrl: 'https://protectorforsikring.no/',
    },
    { logoUrl: '/logos/redhat.svg', name: 'Red Hat', homepageUrl: 'https://www.redhat.com/en' },
    {
        logoUrl: '/logos/rubberduck.svg',
        name: 'Rubberduck Dev AS',
        homepageUrl: 'https://www.rubberduck.no/',
    },
    { logoUrl: '/logos/ruter.svg', name: 'Ruter', homepageUrl: 'https://ruter.no/' },
    { logoUrl: '/logos/safetywing.svg', name: 'SafetyWing', homepageUrl: 'https://safetywing.com/' },
    { logoUrl: '/logos/scelto.svg', name: 'Scelto AS', homepageUrl: 'https://scelto.no/' },
    { logoUrl: '/logos/schibsted.svg', name: 'Schibsted', homepageUrl: 'https://schibsted.com/' },
    { logoUrl: '/logos/scienta.svg', name: 'Scienta ', homepageUrl: 'https://careers.scienta.no/' },
    {
        logoUrl: '/logos/skatteetaten.svg',
        name: 'Skatteetaten',
        homepageUrl: 'https://www.skatteetaten.no/jobb/',
    },
    {
        logoUrl: '/logos/soprasteria.svg',
        name: 'Sopra Steria AS',
        homepageUrl: 'https://www.soprasteria.no/',
    },
    {
        logoUrl: '/logos/sparebank1.svg',
        name: 'SpareBank 1 Utvikling',
        homepageUrl: 'https://sparebank1.dev/',
    },
    {
        logoUrl: '/logos/ssb.svg',
        name: 'SSB - Statistisk Sentralbyrå',
        homepageUrl: 'https://www.ssb.no/',
    },
    {
        logoUrl: '/logos/statensvegvesen.svg',
        name: 'Statens Vegvesen',
        homepageUrl: 'https://www.vegvesen.no/',
    },
    { logoUrl: '/logos/statnett.svg', name: 'Statnett SF', homepageUrl: 'https://www.statnett.no/' },
    {
        logoUrl: '/logos/storebrand.svg',
        name: 'Storebrand',
        homepageUrl: 'https://www.storebrand.no/',
    },
    { logoUrl: '/logos/systek.svg', name: 'Systek', homepageUrl: 'https://www.systek.no/' },
    { logoUrl: '/logos/telenor.svg', name: 'Telenor Norge', homepageUrl: 'https://www.telenor.no/' },
    {
        logoUrl: '/logos/tietoevry.svg',
        name: 'Tietoevry',
        homepageUrl: 'https://www.tietoevry.com/no/',
    },
    { logoUrl: '/logos/tolletaten.svg', name: 'Tolletaten', homepageUrl: 'https://www.toll.no/' },
    { logoUrl: '/logos/tomra.svg', name: 'TOMRA', homepageUrl: 'https://www.tomra.com/' },
    {
        logoUrl: '/logos/tripletex.svg',
        name: 'Tripletex AS',
        homepageUrl: 'https://www.tripletex.no/',
    },
    { logoUrl: '/logos/twoday.svg', name: 'Twoday AS', homepageUrl: 'https://www.twoday.no' },
    {
        logoUrl: '/logos/uptime.svg',
        name: 'Uptime Consulting AS',
        homepageUrl: 'https://www.uptimeconsulting.no/',
    },
    {
        logoUrl: '/logos/variant.svg',
        name: 'Variant Norge AS',
        homepageUrl: 'https://www.variant.no/',
    },
    { logoUrl: '/logos/vivende.svg', name: 'Vivende AS', homepageUrl: 'https://www.vivende.no/' },
    { logoUrl: '/logos/atea.svg', name: 'Atea', homepageUrl: 'https://atea.no/' },
    { logoUrl: '/logos/webstep.svg', name: 'Webstep AS', homepageUrl: 'https://www.webstep.no/' },
    { logoUrl: '/logos/yne.svg', name: 'Yne', homepageUrl: 'https://yne.no/' },
]
